// LIFE.CPP
// Jesse Anderson
// Summer English Writing
/* Although life remains misunderstood by the world as a whole, the code
 for it probably looks something like this.  Not that this can be
 understood. */

const lifespan=78;
typedef sex char;

class human{
 public:
  human::human //constructor for class human
  void life();
 private:
  float in_the_gene_pool();
  virtual void of_being();
  void of_life();
  short time_alive;
  char acter;
  unsigned parents;
  };
human jesse_anderson;

void time(){
 int enough;
 if (!enough){
  exit()}else
	{return enough}; //either way a decision must be made
  };
};

human::human(){
 float in_the_gene_pool();
 time();
 };

float human::in_the_gene_pool(){
sex x;
 parents=2;
 x=random(320);
};

void exist(){
//begin and end
};

void human::life{
 go();
 exist();
};

void day(){
int something,nothing;
 if (something != nothing){
  human.exist();
  };
};

int go(){
 char win_or_lose; //this will remain undefined
 int death,num_of_days;
 while ((num_of_days / 365) < death){
  day();
  num_of_days++;
 };
 return win_or_lose;
};


